version: 2

updates:
  - package-ecosystem: pip
    directory: /
    registries: "*"
    schedule:
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
  - package-ecosystem: docker
    directory: /
    registries: "*"
    schedule:
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
  - package-ecosystem: docker-compose
    directory: /
    registries: "*"
    schedule:
      interval: daily
    labels:
      - "priority: p3 low"
      - "type: dependencies"
      - "status: acknowledged"
